### Регистрация пользователя - успешная (ожидается 200)
# Access token возвращается в JSON теле ответа: {"access_token": "..."}
# Refresh token устанавливается в cookie с именем "refresh_token"
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "email": "test@user.ru",
  "password": "password123"
}

### Регистрация пользователя - дублирующий email (ожидается 409: "Email уже занят")
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "email": "test@user.ru",
  "password": "password456"
}

### Регистрация пользователя - короткий пароль (ожидается 400: "пароль должен содержать минимум 6 символов")
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "email": "test@user.ru",
  "password": "123"
}

### Регистрация пользователя - пустой email (ожидается 400: "email обязателен")
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "email": "",
  "password": "password123"
}

### Регистрация пользователя - невалидный email (ожидается 400: "неверный формат email")
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "email": "test@user_ru",
  "password": "password123"
}

### Регистрация пользователя - невалидный JSON (ожидается 400: "неверный формат запроса")
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "email": "test@user.ru",
  "password": "password123"
}